config/routes.rb
Rails.application.routes.draw do root :to => 'dashboard#index'
  get 'dashboard/index'
  devise_for :users
  resources :clients
  resources :groups
  resources :attendances
  resources :lessons
  resources :periods
  resources :teachers
  resources :languages
  resources :companies
  resources :classrooms
  resources :offices
  resources :posts
  resources :tprices
  resources :cstatuses
  resources :events
  resources :crms

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :client
  belongs_to :lesson
  validates :lesson_id, presence: true
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :office
  has_many :lessons
  def to_s
    name
  end
  validates :name, presence: true
  validates :office, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :attendances
  has_many :lessons, through: :attendances
  belongs_to :language
  belongs_to :office
  belongs_to :cstatus
  has_many :crms

  def to_s
    first_name+" "+last_name
  end
    mount_uploader :photo, PhotoUploader
  validates :first_name, presence: true
  validates :telephone_1, presence: true
  validates :language, presence: true
  validates :office, presence: true



end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :offices
  def to_s
    company_name
  end
   mount_uploader :logo, LogoUploader
  validates :company_name, presence: true
end

app/models/crm.rb
class Crm < ActiveRecord::Base
  belongs_to :client
  belongs_to :teacher
end

app/models/cstatus.rb
class Cstatus < ActiveRecord::Base
  has_many :clients
  def to_s
    cstatus
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :periods
  belongs_to :teacher
  belongs_to :language
  belongs_to :office
  validates :group_name, presence: true
  validates :language, presence: true
  validates :teacher, presence: true
  def to_s
    group_name
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :groups
  has_many :clients
  def to_s
    lang
  end
  validates :lang, presence: true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :attendances, dependent: :destroy
  has_many :clients, through: :attendances
  belongs_to :period
  belongs_to :teacher
  belongs_to :classroom
  validates :period_id, presence: true
  validates :teacher_id, presence: true
  validates :classroom_id, presence: true
  def to_s
    id
  end

end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :classrooms
  has_many :clients
  has_many :groups
  belongs_to :company
  def to_s
    name
  end
  validates :name, presence: true
  validates :company, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
  belongs_to :group
  has_many :lessons, dependent: :destroy
  belongs_to :tprice
  validates :group_id, presence: true
  validates :PeroidDescription, presence: true
  def to_s
    id
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :groups
  has_many :lessons
  has_many :crms
  def to_s
    first_name+" "+last_name
  end
    mount_uploader :photo, PhotoUploader
end

app/models/tprice.rb
class Tprice < ActiveRecord::Base
  has_many :groups
  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @classrooms = @office.classrooms
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name, :company_id, :phone_number, :address, :email)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/offices/_form.html.haml
= simple_form_for(@office) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :company_id, input_html: {value: @office.company_id || params[:company_id]}, as: :hidden
    = f.input :email
    = f.input :phone_number
    = f.input :address

  .form-actions
    = f.button :submit

app/views/offices/edit.html.haml
%h1 Editing office

= render 'form'

= link_to 'Show', @office
\|
= link_to 'Back', offices_path

app/views/offices/index.html.haml
.container
  %h1 Listing offices

  %table.table.table-hover.table-condensed.table-responsive
    %thead
      %tr
        %th Name
        %th Company
        %th Email
        %th Phone number
        %th Address
        %th
        %th
        %th

    %tbody
      - @offices.each do |office|
        %tr
          %td= office.name
          %td= office.company
          %td= office.email
          %td= office.phone_number
          %td= office.address
          %td= link_to 'Show', office, class: 'btn btn-mini btn-success'
          %td= link_to 'Edit', edit_office_path(office), class: 'btn btn-mini btn-warning'
          %td= link_to 'Destroy', office, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'

app/views/offices/new.html.haml
%h1 New office

= render 'form'

= link_to 'Back', offices_path

app/views/offices/show.html.haml
.container
  .row
    .col-md-4
      %h3 Office info
      %p#notice= notice

      %p
        %b Name:
        = @office.name

      = link_to 'Edit', edit_office_path(@office)
      \|
      = link_to 'Back', offices_path

    .col-md-8
      %h3 Listing rooms

      %table.table.table-hover.table-condensed.table-responsive
        %thead
          %tr
            %th Name
            %th Office
            %th
            %th
            %th

        %tbody
          - @classrooms.each do |classroom|
            %tr
              %td= classroom.name
              %td= classroom.office_id
              %td= link_to 'Show', classroom, class: 'btn btn-mini btn-success'
              %td= link_to 'Edit', edit_classroom_path(classroom), class: 'btn btn-mini btn-warning'
              %td= link_to 'Destroy', classroom, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'

      %br

      = link_to 'New Classroom', new_classroom_path(office_id: @office.id), class: 'btn btn-mini btn-success'