config/routes.rb
Rails.application.routes.draw do root :to => 'dashboard#index'
  get 'dashboard/index'
  devise_for :users
  resources :clients
  resources :groups
  resources :attendances
  resources :lessons
  resources :periods
  resources :teachers
  resources :languages
  resources :companies
  resources :classrooms
  resources :offices
  resources :posts
  resources :tprices
  resources :cstatuses
  resources :events
  resources :crms

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :client
  belongs_to :lesson
  validates :lesson_id, presence: true
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :office
  has_many :lessons
  def to_s
    name
  end
  validates :name, presence: true
  validates :office, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :attendances
  has_many :lessons, through: :attendances
  belongs_to :language
  belongs_to :office
  belongs_to :cstatus
  has_many :crms

  def to_s
    first_name+" "+last_name
  end
    mount_uploader :photo, PhotoUploader
  validates :first_name, presence: true
  validates :telephone_1, presence: true
  validates :language, presence: true
  validates :office, presence: true



end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :offices
  def to_s
    company_name
  end
   mount_uploader :logo, LogoUploader
  validates :company_name, presence: true
end

app/models/crm.rb
class Crm < ActiveRecord::Base
  belongs_to :client
  belongs_to :teacher
end

app/models/cstatus.rb
class Cstatus < ActiveRecord::Base
  has_many :clients
  def to_s
    cstatus
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :periods
  belongs_to :teacher
  belongs_to :language
  belongs_to :office
  validates :group_name, presence: true
  validates :language, presence: true
  validates :teacher, presence: true
  def to_s
    group_name
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :groups
  has_many :clients
  def to_s
    lang
  end
  validates :lang, presence: true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :attendances, dependent: :destroy
  has_many :clients, through: :attendances
  belongs_to :period
  belongs_to :teacher
  belongs_to :classroom
  validates :period_id, presence: true
  validates :teacher_id, presence: true
  validates :classroom_id, presence: true
  def to_s
    id
  end

end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :classrooms
  has_many :clients
  has_many :groups
  belongs_to :company
  def to_s
    name
  end
  validates :name, presence: true
  validates :company, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
  belongs_to :group
  has_many :lessons, dependent: :destroy
  belongs_to :tprice
  validates :group_id, presence: true
  validates :PeroidDescription, presence: true
  def to_s
    id
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :groups
  has_many :lessons
  has_many :crms
  def to_s
    first_name+" "+last_name
  end
    mount_uploader :photo, PhotoUploader
end

app/models/tprice.rb
class Tprice < ActiveRecord::Base
  has_many :groups
  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @q = Group.ransack(params[:q])
    @groups = @q.result(distinct: true)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @periods = @group.periods
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name, :teacher_id, :language_id, :office_id, :book_id, :days, :time, :duration, :info)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/_form.html.haml
.container
  = simple_form_for(@group) do |f|
    = f.error_notification

    .form-inputs
      = f.input :group_name
      = f.select :teacher_id, Teacher.all.map{|c| [c, c.id]}, {},class: 'selectize'
      = f.association :language
      = f.association :office
      = f.input :book_id
      = f.input :days
      = f.input :time
      = f.input :duration
      = f.input :info

    .form-actions
      = f.button :submit

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
.container
  %br
  = link_to 'New Group', new_group_path, class: 'btn btn-mini btn-success'
  %h1 All groups

  %table.table.table-hover.table-condensed.table-responsive.container-fluid
    %thead
      %tr
        %th= sort_link @q, :group_name, "Group name"
        %th= sort_link @q, :teacher_id, "Teacher"
        %th= sort_link @q, :language_id, "Language"
        %th= sort_link @q, :office_id, "Office"
        %th Book
        %th Days
        %th Time
        %th Duration
        %th Info
        %th
        %th
        %th

    %tbody
      - @groups.each do |group|
        %tr
          %td= group.group_name
          %td= group.teacher
          %td= group.language
          %td= group.office
          %td= group.book_id
          %td= group.days
          %td= group.time
          %td= group.duration
          %td= group.info
          %td= link_to 'Show', group, class: 'btn btn-mini btn-success'
          %td= link_to 'Edit', edit_group_path(group), class: 'btn btn-mini btn-warning'
          %td= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'

app/views/groups/new.html.haml
.container
  %h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
.container
  .row
    .col-md-4
      %h3 Group info
      %p#notice= notice

      %p
        %b Group name:
        = @group.group_name
      %p
        %b Teacher:
        = @group.teacher
      %p
        %b Language:
        = @group.language
      %p
        %b Office:
        = @group.office
      %p
        %b Book:
        = @group.book_id
      %p
        %b Days:
        = @group.days
      %p
        %b Time:
        = @group.time
      %p
        %b Duration:
        = @group.duration
      %p
        %b Info:
        = @group.info

      = link_to 'Edit', edit_group_path(@group), class: 'btn btn-mini btn-warning'
      \|
      = link_to 'Back', groups_path, class: 'btn btn-mini btn-warning'
    .col-md-8
      %h3 Listing periods
      %table.table.table-hover.table-condensed.table-responsive
        %thead
          %tr
            %th Peroiddescription
            %th Group
            %th Tprice
            %th
            %th
            %th
        %tbody
          - @periods.each do |period|
            %tr
              %td= period.PeroidDescription
              %td= period.group_id
              %td= period.tprice
              %td= link_to 'Show', period, class: 'btn btn-mini btn-success'
              %td= link_to 'Edit', edit_period_path(period), class: 'btn btn-mini btn-warning'
              %td= link_to 'Destroy', period, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'

      %br

      = link_to 'New Period', new_period_path(group_id: @group.id), class: 'btn btn-mini btn-success'