config/routes.rb
Rails.application.routes.draw do root :to => 'dashboard#index'
  get 'dashboard/index'
  devise_for :users
  resources :clients
  resources :groups
  resources :attendances
  resources :lessons
  resources :periods
  resources :teachers
  resources :languages
  resources :companies
  resources :classrooms
  resources :offices
  resources :posts
  resources :tprices
  resources :cstatuses
  resources :events
  resources :crms

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :client
  belongs_to :lesson
  validates :lesson_id, presence: true
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :office
  has_many :lessons
  def to_s
    name
  end
  validates :name, presence: true
  validates :office, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :attendances
  has_many :lessons, through: :attendances
  belongs_to :language
  belongs_to :office
  belongs_to :cstatus
  has_many :crms

  def to_s
    first_name+" "+last_name
  end
    mount_uploader :photo, PhotoUploader
  validates :first_name, presence: true
  validates :telephone_1, presence: true
  validates :language, presence: true
  validates :office, presence: true



end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :offices
  def to_s
    company_name
  end
   mount_uploader :logo, LogoUploader
  validates :company_name, presence: true
end

app/models/crm.rb
class Crm < ActiveRecord::Base
  belongs_to :client
  belongs_to :teacher
end

app/models/cstatus.rb
class Cstatus < ActiveRecord::Base
  has_many :clients
  def to_s
    cstatus
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :periods
  belongs_to :teacher
  belongs_to :language
  belongs_to :office
  validates :group_name, presence: true
  validates :language, presence: true
  validates :teacher, presence: true
  def to_s
    group_name
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :groups
  has_many :clients
  def to_s
    lang
  end
  validates :lang, presence: true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :attendances, dependent: :destroy
  has_many :clients, through: :attendances
  belongs_to :period
  belongs_to :teacher
  belongs_to :classroom
  validates :period_id, presence: true
  validates :teacher_id, presence: true
  validates :classroom_id, presence: true
  def to_s
    id
  end

end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :classrooms
  has_many :clients
  has_many :groups
  belongs_to :company
  def to_s
    name
  end
  validates :name, presence: true
  validates :company, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
  belongs_to :group
  has_many :lessons, dependent: :destroy
  belongs_to :tprice
  validates :group_id, presence: true
  validates :PeroidDescription, presence: true
  def to_s
    id
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :groups
  has_many :lessons
  has_many :crms
  def to_s
    first_name+" "+last_name
  end
    mount_uploader :photo, PhotoUploader
end

app/models/tprice.rb
class Tprice < ActiveRecord::Base
  has_many :groups
  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @offices = @company.offices
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company_name, :website, :phone_number, :address, :logo)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/companies/_form.html.haml
= simple_form_for(@company) do |f|
  = f.error_notification

  .form-inputs
    = f.input :company_name
    = f.input :website
    = f.input :phone_number
    = f.input :address
    = f.input :logo

  .form-actions
    = f.button :submit

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
.container
  %h1 Listing companies

  %table.table.table-hover.table-condensed.table-responsive
    %thead
      %tr
        %th Company name
        %th Website
        %th Phone number
        %th Address
        %th Logo
        %th
        %th
        %th

    %tbody
      - @companies.each do |company|
        %tr
          %td= company.company_name
          %td= company.website
          %td= company.phone_number
          %td= company.address
          %td= image_tag company.logo, size: '30x30'
          %td= link_to 'Show', company, class: 'btn btn-mini btn-success'
          %td= link_to 'Edit', edit_company_path(company), class: 'btn btn-mini btn-warning'
          %td= link_to 'Destroy', company, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'

  %br

  = link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
.container
  .row
    .col-md-4
      %h3 Company info
      %p#notice= notice

      %p
        %b Company name:
        = @company.company_name
      %p
        %b Website:
        = @company.website
      %p
        %b Phone number:
        = @company.phone_number
      %p
        %b Address:
        = @company.address
      %p
        %b Logo:
        = @company.logo

      = link_to 'Edit', edit_company_path(@company)
      \|
      = link_to 'Back', companies_path
    .col-md-8
      %h3 Listing offices

      %table.table.table-hover.table-condensed.table-responsive
        %thead
          %tr
            %th Name
            %th Company
            %th Email
            %th Phone number
            %th Address
            %th
            %th
            %th

        %tbody
          - @offices.each do |office|
            %tr
              %td= office.name
              %td= office.company
              %td= office.email
              %td= office.phone_number
              %td= office.address
              %td= link_to 'Show', office, class: 'btn btn-mini btn-success'
              %td= link_to 'Edit', edit_office_path(office), class: 'btn btn-mini btn-warning'
              %td= link_to 'Destroy', office, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'

      %br

      = link_to 'New Office', new_office_path(company_id: @company.id), class: 'btn btn-mini btn-success'