config/routes.rb
Rails.application.routes.draw do root :to => 'dashboard#index'
  get 'dashboard/index'
  devise_for :users
  resources :clients
  resources :groups
  resources :attendances
  resources :lessons
  resources :periods
  resources :teachers
  resources :languages
  resources :companies
  resources :classrooms
  resources :offices
  resources :posts
  resources :tprices
  resources :cstatuses
  resources :events
  resources :crms

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :client
  belongs_to :lesson
  validates :lesson_id, presence: true
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :office
  has_many :lessons
  def to_s
    name
  end
  validates :name, presence: true
  validates :office, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :attendances
  has_many :lessons, through: :attendances
  belongs_to :language
  belongs_to :office
  belongs_to :cstatus
  has_many :crms

  def to_s
    first_name+" "+last_name
  end
    mount_uploader :photo, PhotoUploader
  validates :first_name, presence: true
  validates :telephone_1, presence: true
  validates :language, presence: true
  validates :office, presence: true



end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :offices
  def to_s
    company_name
  end
   mount_uploader :logo, LogoUploader
  validates :company_name, presence: true
end

app/models/crm.rb
class Crm < ActiveRecord::Base
  belongs_to :client
  belongs_to :teacher
end

app/models/cstatus.rb
class Cstatus < ActiveRecord::Base
  has_many :clients
  def to_s
    cstatus
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :periods
  belongs_to :teacher
  belongs_to :language
  belongs_to :office
  validates :group_name, presence: true
  validates :language, presence: true
  validates :teacher, presence: true
  def to_s
    group_name
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :groups
  has_many :clients
  def to_s
    lang
  end
  validates :lang, presence: true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :attendances, dependent: :destroy
  has_many :clients, through: :attendances
  belongs_to :period
  belongs_to :teacher
  belongs_to :classroom
  validates :period_id, presence: true
  validates :teacher_id, presence: true
  validates :classroom_id, presence: true
  def to_s
    id
  end

end

app/models/office.rb
class Office < ActiveRecord::Base
  has_many :classrooms
  has_many :clients
  has_many :groups
  belongs_to :company
  def to_s
    name
  end
  validates :name, presence: true
  validates :company, presence: true
end

app/models/period.rb
class Period < ActiveRecord::Base
  belongs_to :group
  has_many :lessons, dependent: :destroy
  belongs_to :tprice
  validates :group_id, presence: true
  validates :PeroidDescription, presence: true
  def to_s
    id
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :groups
  has_many :lessons
  has_many :crms
  def to_s
    first_name+" "+last_name
  end
    mount_uploader :photo, PhotoUploader
end

app/models/tprice.rb
class Tprice < ActiveRecord::Base
  has_many :groups
  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @lessons = @teacher.lessons
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :middle_name, :last_name, :birthdate, :telephone_1, :email, :info, :photo)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.haml
= simple_form_for(@teacher) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :middle_name
    = f.input :last_name
    = f.date_select :birthdate, :start_year => Time.now.year - 60, :end_year => Time.now.year - 18
    = f.input :telephone_1
    = f.input :email
    = f.input :info
    = f.input :photo

  .form-actions
    = f.button :submit

app/views/teachers/edit.html.haml
%h1 Editing teacher

= render 'form'

= link_to 'Show', @teacher
\|
= link_to 'Back', teachers_path

app/views/teachers/index.html.haml
.container
  %br
  = link_to 'Invite Teacher', new_teacher_path, class: 'btn btn-mini btn-warning'
  %br
  %h1 Listing teachers

  %table.table.table-hover.table-condensed.table-responsive
    %thead
      %tr
        %th First name
        %th Middle name
        %th Last name
        %th Birthdate
        %th Telephone 1
        %th Email
        %th Info
        %th Photo
        %th
        %th
        %th

    %tbody
      - @teachers.each do |teacher|
        %tr
          %td= teacher.first_name
          %td= teacher.middle_name
          %td= teacher.last_name
          %td= teacher.birthdate
          %td= teacher.telephone_1
          %td= teacher.email
          %td= teacher.info
          %td= image_tag teacher.photo, size: '30x30'
          %td= link_to 'Show', teacher, class: 'btn btn-mini btn-success'
          %td= link_to 'Edit', edit_teacher_path(teacher), class: 'btn btn-mini btn-warning'
          %td= link_to 'Destroy', teacher, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'

app/views/teachers/new.html.haml
%h1 New teacher

= render 'form'

= link_to 'Back', teachers_path

app/views/teachers/show.html.haml
.container
  .row
    .col-md-4
      %h1 Teacher info
      %p#notice= notice
      %p
        %b Photo:
        = image_tag @teacher.photo, size: '190x190', class: 'img-circle'
      = link_to 'Edit', edit_teacher_path(@teacher), class: 'btn btn-mini btn-warning'
      \|
      = link_to 'Back', teachers_path, class: 'btn btn-mini btn-warning'
      %p
        %b First name:
        = @teacher.first_name
      %p
        %b Middle name:
        = @teacher.middle_name
      %p
        %b Last name:
        = @teacher.last_name
      %p
        %b Birthdate:
        = @teacher.birthdate
      %p
        %b Telephone 1:
        = @teacher.telephone_1
      %p
        %b Email:
        = @teacher.email
      %p
        %b Info:
        = @teacher.info
    .col-md-8
      %h1 Listing lessons

      %table.table.table-hover.table-condensed.table-responsive
        %thead
          %tr
            %th Start time
            %th Group
            %th Period
            %th Classroom
            %th Tarif
            %th
            %th
            %th

        %tbody
          - @lessons.each do |lesson|
            %tr
              %td= lesson.start_time
              %td= lesson.period.group.group_name
              %td= lesson.period_id
              %td= lesson.classroom
              %td= lesson.period.tprice.tprice
              %td= link_to 'Show', lesson, class: 'btn btn-mini btn-success'
              %td= link_to 'Edit', edit_lesson_path(lesson), class: 'btn btn-mini btn-warning'
              %td= link_to 'Destroy', lesson, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-mini btn-danger'